# Site settings

# Tell github not to auto-regen Jekyll:
include:
  - .nojekyll
exclude:
  - "Gruntfile.js"
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"

title: Kirk the Software Developer and Blogger | also known as saricDen
email: no@saricden.com
description: > # this means to ignore newlines until "baseurl:"
  You found me! Like coding and/or blogs? Welcome to my site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saricden.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: pretty

# Build settings
markdown: kramdown
